### ISSUE TITLE
Rendered extension manager blank

### ISSUE THREAD

**Issue by xyohst** [akeeba/magiceraser#1]
Just a white screen on extensions > manage > manage, plugins, global configuration after running the script

Joomla 3.10.10
PHP 7.4

Both public HTML (Plesk) and localhost (MAMP)

(luckily, I have a restore file)

**Comment by nikosdion** [comment]
You have a third party extension using an ancient extension of ours, probably an ancient version of FOF (2.x discontinued 2015 or 3.x discontinued 2020). Nothing we can really do about that. We gave third party developers plenty of advance notice every time, well over a year for each version.
