### ISSUE TITLE
Broken Link / Incorrect Path to Download this 

### ISSUE THREAD

**Issue by M4dKiwi** [akeeba/magiceraser#2]
Steps to recreate 
#1: https://www.akeeba.com/download.html  ...... 
#2: click on Download link ( Path = https://github.com/akeeba/magiceraser/latest )
Result = 404 Error - this is not the web page your looking for 

No doubt an easy thing to correct , I just thought I'd point it out as I was a little disappointed I could not download
but I'm looking forward to doing it as soon as its available for download :)  

- Thanks ,Your products are a lifesaver
(maybe more like a time saver, without them I'd loose months worth of sleepless nights - would all be lost down the digital gurgler!)

**Comment by nikosdion** [comment]
GitHub has changed the URL scheme for downloads. Sigh.

The new URL is https://github.com/akeeba/magiceraser/releases/latest
